name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    env:
      NEXT_PUBLIC_SERVE: "https://example.com"
      NEXT_PUBLIC_SERVE_1: "https://example.com"
      NEXT_PUBLIC_SERVE_2: "https://example.com"
      NEXT_PUBLIC_SERVE_3: "https://example.com"
      NEXT_PUBLIC_SERVE_4: "https://example.com"
      NEXT_PUBLIC_SERVE_5: "https://example.com"
      NEXT_PUBLIC_SERVE_6: "https://example.com"
      NEXT_PUBLIC_SERVE_7: "https://example.com"
      NEXT_PUBLIC_SERVE_8: "https://example.com"
      NEXT_PUBLIC_SERVE_9: "https://example.com"

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
